# Generated by Django 2.0.4 on 2018-06-06 20:53

import chigre.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chigre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brewery',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=models.SET(chigre.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brewery',
            name='logo',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
