# Generated by Django 2.0.4 on 2018-06-07 19:08

import chigre.models.common
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chigre', '0002_auto_20180606_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='KegType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('size', models.DecimalField(decimal_places=2, max_digits=3)),
                ('pints', models.IntegerField()),
                ('canyas', models.IntegerField()),
                ('creator', models.ForeignKey(on_delete=models.SET(chigre.models.common.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
