# Generated by Django 2.0.4 on 2018-06-08 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chigre', '0005_beertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beertype',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
