# Generated by Django 2.0.4 on 2018-06-08 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chigre', '0006_auto_20180608_2344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beertype',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='beertype',
            name='created',
        ),
        migrations.RemoveField(
            model_name='beertype',
            name='creator',
        ),
    ]
