# Generated by Django 2.0.4 on 2018-06-08 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chigre', '0007_auto_20180608_2351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kegtype',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='kegtype',
            name='created',
        ),
        migrations.RemoveField(
            model_name='kegtype',
            name='creator',
        ),
    ]
