# Generated by Django 2.0.4 on 2018-06-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chigre', '0011_auto_20180610_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='TapType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
