# Generated by Django 2.0.4 on 2018-06-10 12:08

import chigre.models.common
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chigre', '0012_taptype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('number', models.IntegerField()),
                ('photo', models.CharField(blank=True, default='', max_length=100)),
                ('beer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chigre.Beer')),
                ('creator', models.ForeignKey(on_delete=models.SET(chigre.models.common.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
                ('taptype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chigre.TapType')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
