# Generated by Django 2.0.4 on 2018-06-10 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chigre', '0013_tap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tap',
            name='beer',
        ),
        migrations.AddField(
            model_name='tap',
            name='keg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chigre.Keg'),
        ),
    ]
