# Generated by Django 2.0.6 on 2018-06-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chigre', '0015_brewery_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_enforce', models.IntegerField(default=1, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('address', models.TextField(blank=True, default='')),
                ('webpage', models.CharField(blank=True, default='', max_length=100)),
                ('logo', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
