# Generated by Django 2.0.7 on 2018-07-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chigre', '0020_auto_20180716_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pub',
            name='webpage',
        ),
        migrations.AddField(
            model_name='pub',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
