# Generated by Django 2.0.7 on 2018-07-16 15:38

import chigre.models.common
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chigre', '0021_auto_20180716_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='pub',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pub',
            name='updater',
            field=models.ForeignKey(default=1, on_delete=models.SET(chigre.models.common.get_sentinel_user), to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
