# Generated by Django 2.0.7 on 2018-07-16 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chigre', '0023_auto_20180716_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pub',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='pub',
            name='updater',
        ),
    ]
