# Generated by Django 2.0.7 on 2018-07-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chigre', '0025_pubgallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pub',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='pub',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=20, null=True),
        ),
    ]
